version: 2.1

orbs:
  win: circleci/windows@2.2.0

default_steps: &default_steps
  working_directory: ~/Job_Shop_Schedule_Problem
  steps:
    - checkout
    - run:
        name: Get Dependencies
        command: pip install -r requirements.txt
    - run:
        name: Build Cython
        command: python setup.py build_ext
    - run:
        name: Unit Tests
        command: python -m unittest discover -s ./tests/unit_tests
    - run:
        name: Functional Tests
        command: python -m unittest discover -s ./tests/functional_tests

jobs:
  windows-build-and-test:
    executor:
      name: win/default
      shell: bash.exe
    <<: *default_steps

  linux-build-and-test:
    docker:
      - image: circleci/python:3.6
    <<: *default_steps

workflows:
  tests:
    jobs:
      - windows-build-and-test:
          name: "Windows Build and Test"
      - linux-build-and-test:
          name: "Linux Build and Test"
